FROM python:3

WORKDIR /home

# パッケージリストにchrome追加
RUN sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
# 公開鍵の登録
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN apt update
RUN apt install -y google-chrome-stable
RUN pip install --upgrade pip
RUN python -m pip install selenium
RUN python -m pip install webdriver-manager
RUN python -m pip install jpholiday
RUN python -m pip install python-dateutil
